CREATE DATABASE DBMS_ASSIGNMENT1;

USE DBMS_ASSIGNMENT1;

CREATE TABLE CLIENT_MASTER (
    Client_No VARCHAR(6) PRIMARY KEY,
    Name VARCHAR(20) NOT NULL,
    City VARCHAR(15) NOT NULL,
    State VARCHAR(15),
    Pincode INT CHECK (Pincode BETWEEN 100000 AND 999999),
    Bal_Due DECIMAL(10,2) CHECK (Bal_Due >= 0)
);

CREATE TABLE ORDERS (
    Order_No INT PRIMARY KEY,
    Client_No VARCHAR(6) NOT NULL,
    Order_Date DATE,
    Order_Amount DECIMAL(8,2) CHECK (Order_Amount > 0),
    CONSTRAINT fk_orders_client 
    FOREIGN KEY (Client_No) 
    REFERENCES CLIENT_MASTER(Client_No)
);

ALTER TABLE CLIENT_MASTER ADD DOB DATE;


ALTER TABLE CLIENT_MASTER MODIFY Pincode BIGINT;
ALTER TABLE CLIENT_MASTER MODIFY Bal_Due DECIMAL(12,2);

ALTER TABLE CLIENT_MASTER RENAME COLUMN State TO State_Name;

ALTER TABLE CLIENT_MASTER DROP COLUMN DOB;


ALTER TABLE CLIENT_MASTER 
ADD CONSTRAINT unique_name_city UNIQUE (Name, City);

ALTER TABLE CLIENT_MASTER 
DROP INDEX unique_name_city;


ALTER TABLE ORDERS 
ADD CONSTRAINT chk_amount 
CHECK (Order_Amount BETWEEN 1 AND 100000);

SET FOREIGN_KEY_CHECKS = 0;

SET FOREIGN_KEY_CHECKS = 1;


ALTER TABLE ORDERS DROP FOREIGN KEY fk_orders_client;


ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_client
FOREIGN KEY (Client_No)
REFERENCES CLIENT_MASTER(Client_No)
ON DELETE CASCADE;

ALTER TABLE ORDERS DROP PRIMARY KEY;

ALTER TABLE ORDERS ADD PRIMARY KEY (Order_No);


RENAME TABLE ORDERS TO ORDER_MASTER;
RENAME TABLE CLIENT_MASTER TO CLIENTS;

CREATE INDEX idx_city ON CLIENT_MASTER(City);

DROP INDEX idx_city ON CLIENT_MASTER;

CREATE VIEW V_CLIENT_BALANCE AS
SELECT Client_No, Name, Bal_Due
FROM CLIENT_MASTER;


CREATE OR REPLACE VIEW V_CLIENT_BALANCE AS
SELECT Client_No, Name, Bal_Due
FROM CLIENT_MASTER
WHERE Bal_Due > 0;


DROP VIEW V_CLIENT_BALANCE;

ALTER TABLE ORDER_MASTER 
ADD Status VARCHAR(10) DEFAULT 'PENDING';

ALTER TABLE ORDER_MASTER 
MODIFY Status VARCHAR(20);

ALTER TABLE ORDER_MASTER 
DROP CHECK order_master_chk_1;

ALTER TABLE ORDER_MASTER
RENAME COLUMN Order_Amount TO Amount;

ALTER TABLE ORDER_MASTER 
ADD CONSTRAINT chk_amount 
CHECK (Amount BETWEEN 1 AND 100000);


ALTER TABLE ORDER_MASTER 
DROP COLUMN Status;


RENAME TABLE ORDER_MASTER TO ORDERS;
RENAME TABLE CLIENTS_202510116100093 TO CLIENT_MASTER;








